"""
Mock data for the Emporyum Tech tech challenge.
In production, this data would come from a database / data warehouse.
The fetch_user_data node should use MOCK_USERS to look up user data by user_id.
The product catalog (MOCK_CATALOG) is available for recommendation agents.
"""


INSTALLMENT_PLANS = {
    1: {"months": 1, "monthly_rate": 0.0, "description": "Pago unico sin intereses"},
    3: {"months": 3, "monthly_rate": 1.2, "description": "3 cuotas - 1.2% mensual"},
    6: {"months": 6, "monthly_rate": 1.5, "description": "6 cuotas - 1.5% mensual"},
    12: {"months": 12, "monthly_rate": 1.8, "description": "12 cuotas - 1.8% mensual"},
    24: {"months": 24, "monthly_rate": 2.0, "description": "24 cuotas - 2.0% mensual"},
}


ACTIVE_PROMOTIONS = [
    {"name": "Tech Week", "discount": "15% de descuento en electronica", "valid_until": "2025-03-01", "category": "electronics"},
    {"name": "Nuevo Usuario", "discount": "10% en tu primera compra", "valid_until": "2025-12-31", "category": "all"},
    {"name": "Envio Gratis", "discount": "Envio gratis en compras mayores a $200,000", "valid_until": "2025-12-31", "category": "all"},
    {"name": "Beauty Days", "discount": "20% en productos de belleza seleccionados", "valid_until": "2025-03-15", "category": "beauty"},
    {"name": "Hogar Feliz", "discount": "Hasta 30% en articulos para el hogar", "valid_until": "2025-02-28", "category": "home"},
]


MOCK_USERS = {
    "user_001": {
        "primer_nombre": "Carlos",
        "email": "carlos.martinez@gmail.com",
        "phone": "+573101234567",
        "email_verified": True,
        "phone_verified": True,
        "account_status": "active",
        "delivery_address_city": "Bogota",
        "purchase_history": ["electronics", "electronics", "home"],
        "user_category_preferences": ["electronics", "home"],
        "orders": [
            {
                "order_id": "ORD-2025-001",
                "product_name": "Audifonos inalambricos Sony WH-1000XM5",
                "product_category": "electronics",
                "price": 1499000,
                "installment_plan": 6,
                "monthly_payment": 271820,
                "interest_rate_monthly": 1.5,
                "status": "DELIVERED",
                "order_date": "2024-11-10",
                "delivery_date": "2024-11-18",
                "return_eligible": False,
                "outstanding_balance": 0,
                "payment_due_date": None,
                "payments_made": 6,
                "payments_remaining": 0,
            },
            {
                "order_id": "ORD-2025-012",
                "product_name": "Laptop ASUS ROG Strix G16",
                "product_category": "electronics",
                "price": 5899000,
                "installment_plan": 12,
                "monthly_payment": 548270,
                "interest_rate_monthly": 1.8,
                "status": "IN_TRANSIT",
                "order_date": "2025-02-10",
                "delivery_date": None,
                "return_eligible": False,
                "outstanding_balance": 5351130,
                "payment_due_date": "2025-03-10",
                "payments_made": 1,
                "payments_remaining": 11,
            },
        ],
        "available_promotions": [
            {"name": "Tech Week", "discount": "15% de descuento en electronica", "valid_until": "2025-03-01"},
        ],
    },
    "user_002": {
        "primer_nombre": "Maria",
        "email": "maria.lopez@hotmail.com",
        "phone": "+573209876543",
        "email_verified": True,
        "phone_verified": True,
        "account_status": "active",
        "delivery_address_city": "Medellin",
        "purchase_history": ["fashion"],
        "user_category_preferences": ["fashion", "beauty"],
        "orders": [
            {
                "order_id": "ORD-2025-023",
                "product_name": "Bolso de cuero italiano marca Velez",
                "product_category": "fashion",
                "price": 389000,
                "installment_plan": 3,
                "monthly_payment": 134690,
                "interest_rate_monthly": 1.2,
                "status": "DELIVERED",
                "order_date": "2024-12-20",
                "delivery_date": "2024-12-28",
                "return_eligible": False,
                "outstanding_balance": 0,
                "payment_due_date": None,
                "payments_made": 3,
                "payments_remaining": 0,
            },
        ],
        "available_promotions": [
            {"name": "Nuevo Usuario", "discount": "10% en tu primera compra", "valid_until": "2025-12-31"},
        ],
    },
    "user_003": {
        "primer_nombre": "Andres",
        "email": "andres.garcia@yahoo.com",
        "phone": "+573155551234",
        "email_verified": True,
        "phone_verified": False,
        "account_status": "active",
        "delivery_address_city": "Cali",
        "purchase_history": [],
        "user_category_preferences": [],
        "orders": [],
        "available_promotions": [
            {"name": "Nuevo Usuario", "discount": "10% en tu primera compra", "valid_until": "2025-12-31"},
            {"name": "Envio Gratis", "discount": "Envio gratis en compras mayores a $200,000", "valid_until": "2025-12-31"},
        ],
    },
    "user_004": {
        "primer_nombre": "Valentina",
        "email": "valentina.r@gmail.com",
        "phone": "+573001112233",
        "email_verified": True,
        "phone_verified": True,
        "account_status": "active",
        "delivery_address_city": "Barranquilla",
        "purchase_history": ["fashion", "beauty", "home", "electronics"],
        "user_category_preferences": ["fashion", "beauty", "home"],
        "orders": [
            {
                "order_id": "ORD-2025-034",
                "product_name": "Vestido de fiesta marca Ela",
                "product_category": "fashion",
                "price": 259000,
                "installment_plan": 3,
                "monthly_payment": 89630,
                "interest_rate_monthly": 1.2,
                "status": "DELIVERED",
                "order_date": "2024-12-01",
                "delivery_date": "2024-12-09",
                "return_eligible": False,
                "outstanding_balance": 89630,
                "payment_due_date": "2025-02-01",
                "payments_made": 2,
                "payments_remaining": 1,
            },
            {
                "order_id": "ORD-2025-045",
                "product_name": "Set de ollas antiadherentes T-fal",
                "product_category": "home",
                "price": 449000,
                "installment_plan": 6,
                "monthly_payment": 81370,
                "interest_rate_monthly": 1.5,
                "status": "SHIPPED",
                "order_date": "2025-02-08",
                "delivery_date": None,
                "return_eligible": False,
                "outstanding_balance": 406850,
                "payment_due_date": "2025-03-08",
                "payments_made": 1,
                "payments_remaining": 5,
            },
            {
                "order_id": "ORD-2025-056",
                "product_name": "Paleta de sombras Urban Decay Naked",
                "product_category": "beauty",
                "price": 189000,
                "installment_plan": 1,
                "monthly_payment": 189000,
                "interest_rate_monthly": 0.0,
                "status": "PREPARING",
                "order_date": "2025-02-14",
                "delivery_date": None,
                "return_eligible": False,
                "outstanding_balance": 189000,
                "payment_due_date": "2025-03-14",
                "payments_made": 0,
                "payments_remaining": 1,
            },
        ],
        "available_promotions": [
            {"name": "Beauty Days", "discount": "20% en productos de belleza seleccionados", "valid_until": "2025-03-15"},
        ],
    },
    "user_005": {
        "primer_nombre": "Santiago",
        "email": "santiago.perez@outlook.com",
        "phone": "+573178889900",
        "email_verified": True,
        "phone_verified": True,
        "account_status": "active",
        "delivery_address_city": "Bogota",
        "purchase_history": ["home"],
        "user_category_preferences": ["home", "electronics"],
        "orders": [
            {
                "order_id": "ORD-2025-067",
                "product_name": "Aspiradora robot iRobot Roomba i3",
                "product_category": "home",
                "price": 1299000,
                "installment_plan": 12,
                "monthly_payment": 120460,
                "interest_rate_monthly": 1.8,
                "status": "CANCELLED",
                "order_date": "2025-01-20",
                "delivery_date": None,
                "return_eligible": False,
                "outstanding_balance": 0,
                "payment_due_date": None,
                "payments_made": 0,
                "payments_remaining": 0,
            },
        ],
        "available_promotions": [
            {"name": "Hogar Feliz", "discount": "Hasta 30% en articulos para el hogar", "valid_until": "2025-02-28"},
        ],
    },
    "user_006": {
        "primer_nombre": "Camila",
        "email": "camila.torres@gmail.com",
        "phone": "+573124445566",
        "email_verified": True,
        "phone_verified": True,
        "account_status": "active",
        "delivery_address_city": "Cartagena",
        "purchase_history": ["beauty", "beauty"],
        "user_category_preferences": ["beauty", "fashion"],
        "orders": [
            {
                "order_id": "ORD-2025-078",
                "product_name": "Kit de skincare The Ordinary completo",
                "product_category": "beauty",
                "price": 245000,
                "installment_plan": 3,
                "monthly_payment": 84780,
                "interest_rate_monthly": 1.2,
                "status": "DELIVERED",
                "order_date": "2025-02-08",
                "delivery_date": "2025-02-15",
                "return_eligible": True,
                "outstanding_balance": 169560,
                "payment_due_date": "2025-03-08",
                "payments_made": 1,
                "payments_remaining": 2,
            },
        ],
        "available_promotions": [
            {"name": "Beauty Days", "discount": "20% en productos de belleza seleccionados", "valid_until": "2025-03-15"},
        ],
    },
    "user_007": {
        "primer_nombre": "Diego",
        "email": "diego.ramirez@gmail.com",
        "phone": "+573167778899",
        "email_verified": True,
        "phone_verified": True,
        "account_status": "active",
        "delivery_address_city": "Bucaramanga",
        "purchase_history": ["electronics", "home", "electronics", "electronics", "home"],
        "user_category_preferences": ["electronics", "home"],
        "orders": [
            {
                "order_id": "ORD-2025-089",
                "product_name": "Smart TV Samsung 55 pulgadas 4K",
                "product_category": "electronics",
                "price": 2199000,
                "installment_plan": 12,
                "monthly_payment": 204070,
                "interest_rate_monthly": 1.8,
                "status": "DELIVERED",
                "order_date": "2024-06-15",
                "delivery_date": "2024-06-22",
                "return_eligible": False,
                "outstanding_balance": 0,
                "payment_due_date": None,
                "payments_made": 12,
                "payments_remaining": 0,
            },
            {
                "order_id": "ORD-2025-090",
                "product_name": "Escritorio de madera ajustable en altura",
                "product_category": "home",
                "price": 899000,
                "installment_plan": 6,
                "monthly_payment": 162920,
                "interest_rate_monthly": 1.5,
                "status": "DELIVERED",
                "order_date": "2024-08-01",
                "delivery_date": "2024-08-10",
                "return_eligible": False,
                "outstanding_balance": 0,
                "payment_due_date": None,
                "payments_made": 6,
                "payments_remaining": 0,
            },
            {
                "order_id": "ORD-2025-091",
                "product_name": "Teclado mecanico Logitech MX Keys",
                "product_category": "electronics",
                "price": 549000,
                "installment_plan": 3,
                "monthly_payment": 190050,
                "interest_rate_monthly": 1.2,
                "status": "DELIVERED",
                "order_date": "2024-10-05",
                "delivery_date": "2024-10-12",
                "return_eligible": False,
                "outstanding_balance": 0,
                "payment_due_date": None,
                "payments_made": 3,
                "payments_remaining": 0,
            },
            {
                "order_id": "ORD-2025-092",
                "product_name": "Lampara de pie inteligente Philips Hue",
                "product_category": "home",
                "price": 379000,
                "installment_plan": 1,
                "monthly_payment": 379000,
                "interest_rate_monthly": 0.0,
                "status": "DELIVERED",
                "order_date": "2025-01-05",
                "delivery_date": "2025-01-13",
                "return_eligible": False,
                "outstanding_balance": 0,
                "payment_due_date": None,
                "payments_made": 1,
                "payments_remaining": 0,
            },
        ],
        "available_promotions": [
            {"name": "Tech Week", "discount": "15% de descuento en electronica", "valid_until": "2025-03-01"},
            {"name": "Hogar Feliz", "discount": "Hasta 30% en articulos para el hogar", "valid_until": "2025-02-28"},
        ],
    },
    "user_008": {
        "primer_nombre": "Laura",
        "email": "laura.gomez@gmail.com",
        "phone": "+573193334455",
        "email_verified": False,
        "phone_verified": True,
        "account_status": "active",
        "delivery_address_city": "Pereira",
        "purchase_history": ["fashion"],
        "user_category_preferences": ["fashion"],
        "orders": [
            {
                "order_id": "ORD-2025-099",
                "product_name": "Zapatillas Nike Air Max 90",
                "product_category": "fashion",
                "price": 549000,
                "installment_plan": 6,
                "monthly_payment": 99500,
                "interest_rate_monthly": 1.5,
                "status": "CONFIRMED",
                "order_date": "2025-02-14",
                "delivery_date": None,
                "return_eligible": False,
                "outstanding_balance": 549000,
                "payment_due_date": "2025-03-14",
                "payments_made": 0,
                "payments_remaining": 6,
            },
        ],
        "available_promotions": [
            {"name": "Nuevo Usuario", "discount": "10% en tu primera compra", "valid_until": "2025-12-31"},
        ],
    },
}


# ---------------------------------------------------------------------------
# MOCK_CATALOG - ~300 products across 4 categories
# ---------------------------------------------------------------------------

MOCK_CATALOG = [
    # ===================================================================
    # ELECTRONICS (~80 products) - PROD-0001 to PROD-0080
    # ===================================================================
    # -- smartphones --
    {"product_id": "PROD-0001", "name": "Samsung Galaxy S24 Ultra 256GB", "price": 5499000, "category": "electronics", "subcategory": "smartphones", "rating": 4.8, "in_stock": True, "trending": True, "description": "Smartphone premium con S Pen integrado y camara de 200MP"},
    {"product_id": "PROD-0002", "name": "iPhone 15 Pro Max 256GB", "price": 6299000, "category": "electronics", "subcategory": "smartphones", "rating": 4.9, "in_stock": True, "trending": True, "description": "El iPhone mas avanzado con chip A17 Pro y titanio"},
    {"product_id": "PROD-0003", "name": "Xiaomi Redmi Note 13 Pro", "price": 1299000, "category": "electronics", "subcategory": "smartphones", "rating": 4.5, "in_stock": True, "trending": True, "description": "Smartphone con camara de 200MP y carga rapida de 67W"},
    {"product_id": "PROD-0004", "name": "Motorola Edge 40 Neo", "price": 1599000, "category": "electronics", "subcategory": "smartphones", "rating": 4.3, "in_stock": True, "trending": False, "description": "Smartphone 5G con pantalla pOLED de 144Hz curva"},
    {"product_id": "PROD-0005", "name": "Samsung Galaxy A54 5G", "price": 1699000, "category": "electronics", "subcategory": "smartphones", "rating": 4.4, "in_stock": True, "trending": False, "description": "Smartphone resistente al agua con bateria de larga duracion"},
    {"product_id": "PROD-0006", "name": "iPhone 15 128GB", "price": 4199000, "category": "electronics", "subcategory": "smartphones", "rating": 4.7, "in_stock": True, "trending": False, "description": "iPhone con Dynamic Island y camara de 48MP mejorada"},
    {"product_id": "PROD-0007", "name": "OPPO Reno 10 Pro", "price": 1899000, "category": "electronics", "subcategory": "smartphones", "rating": 4.2, "in_stock": True, "trending": False, "description": "Smartphone con zoom teleobjetivo y carga rapida SUPERVOOC"},
    {"product_id": "PROD-0008", "name": "Google Pixel 8 128GB", "price": 3299000, "category": "electronics", "subcategory": "smartphones", "rating": 4.6, "in_stock": True, "trending": False, "description": "Smartphone con inteligencia artificial avanzada de Google"},
    {"product_id": "PROD-0009", "name": "Huawei Nova 12i", "price": 899000, "category": "electronics", "subcategory": "smartphones", "rating": 4.0, "in_stock": True, "trending": False, "description": "Smartphone economico con pantalla OLED y buen rendimiento"},
    {"product_id": "PROD-0010", "name": "Realme 11 Pro 5G", "price": 1399000, "category": "electronics", "subcategory": "smartphones", "rating": 4.1, "in_stock": False, "trending": False, "description": "Smartphone 5G con diseno curvo y camara de 100MP"},
    # -- laptops --
    {"product_id": "PROD-0011", "name": "Laptop ASUS ROG Strix G16 RTX 4060", "price": 5899000, "category": "electronics", "subcategory": "laptops", "rating": 4.7, "in_stock": True, "trending": True, "description": "Portatil gamer con procesador Intel i9 y pantalla 165Hz"},
    {"product_id": "PROD-0012", "name": "MacBook Air M2 13 pulgadas", "price": 5499000, "category": "electronics", "subcategory": "laptops", "rating": 4.9, "in_stock": True, "trending": True, "description": "Ultrabook Apple con chip M2 y bateria de 18 horas"},
    {"product_id": "PROD-0013", "name": "Lenovo IdeaPad 3 15 pulgadas", "price": 1899000, "category": "electronics", "subcategory": "laptops", "rating": 4.3, "in_stock": True, "trending": False, "description": "Portatil versatil para estudio y trabajo con buena autonomia"},
    {"product_id": "PROD-0014", "name": "HP Pavilion 15 AMD Ryzen 5", "price": 2399000, "category": "electronics", "subcategory": "laptops", "rating": 4.2, "in_stock": True, "trending": False, "description": "Laptop con procesador AMD Ryzen 5 y 16GB de RAM"},
    {"product_id": "PROD-0015", "name": "Dell Inspiron 14 Intel i5", "price": 2799000, "category": "electronics", "subcategory": "laptops", "rating": 4.4, "in_stock": True, "trending": False, "description": "Portatil delgado con pantalla FHD y teclado retroiluminado"},
    {"product_id": "PROD-0016", "name": "Acer Nitro 5 RTX 3050", "price": 3999000, "category": "electronics", "subcategory": "laptops", "rating": 4.5, "in_stock": True, "trending": False, "description": "Laptop gamer con refrigeracion avanzada y pantalla 144Hz"},
    {"product_id": "PROD-0017", "name": "Laptop HP Victus 16 Gaming", "price": 4299000, "category": "electronics", "subcategory": "laptops", "rating": 4.3, "in_stock": True, "trending": False, "description": "Portatil gamer con pantalla 16 pulgadas y audio mejorado"},
    {"product_id": "PROD-0018", "name": "MacBook Pro M3 14 pulgadas", "price": 7999000, "category": "electronics", "subcategory": "laptops", "rating": 4.9, "in_stock": True, "trending": True, "description": "MacBook Pro profesional con chip M3 y pantalla Liquid Retina"},
    {"product_id": "PROD-0019", "name": "Chromebook Lenovo IdeaPad Duet", "price": 1199000, "category": "electronics", "subcategory": "laptops", "rating": 3.9, "in_stock": True, "trending": False, "description": "Chromebook 2 en 1 con pantalla tactil y teclado desmontable"},
    {"product_id": "PROD-0020", "name": "ASUS VivoBook 15 OLED", "price": 2999000, "category": "electronics", "subcategory": "laptops", "rating": 4.5, "in_stock": False, "trending": False, "description": "Portatil con pantalla OLED vivida y procesador Intel i7"},
    # -- audio --
    {"product_id": "PROD-0021", "name": "Audifonos Sony WH-1000XM5", "price": 1499000, "category": "electronics", "subcategory": "audio", "rating": 4.8, "in_stock": True, "trending": True, "description": "Audifonos con cancelacion de ruido lider y sonido premium"},
    {"product_id": "PROD-0022", "name": "AirPods Pro 2da generacion", "price": 1099000, "category": "electronics", "subcategory": "audio", "rating": 4.7, "in_stock": True, "trending": True, "description": "Audifonos Apple con audio espacial y cancelacion activa"},
    {"product_id": "PROD-0023", "name": "Parlante JBL Charge 5", "price": 599000, "category": "electronics", "subcategory": "audio", "rating": 4.6, "in_stock": True, "trending": False, "description": "Parlante portatil resistente al agua con 20 horas de bateria"},
    {"product_id": "PROD-0024", "name": "Audifonos Samsung Galaxy Buds2 Pro", "price": 699000, "category": "electronics", "subcategory": "audio", "rating": 4.4, "in_stock": True, "trending": False, "description": "Audifonos inalambricos con audio Hi-Fi y ajuste ergonomico"},
    {"product_id": "PROD-0025", "name": "Barra de sonido Samsung HW-Q600B", "price": 1299000, "category": "electronics", "subcategory": "audio", "rating": 4.5, "in_stock": True, "trending": False, "description": "Barra de sonido con Dolby Atmos y subwoofer inalambrico"},
    {"product_id": "PROD-0026", "name": "Parlante Bose SoundLink Flex", "price": 549000, "category": "electronics", "subcategory": "audio", "rating": 4.5, "in_stock": True, "trending": False, "description": "Parlante Bluetooth portatil con sonido potente y resistente"},
    {"product_id": "PROD-0027", "name": "Audifonos Beats Studio Pro", "price": 1399000, "category": "electronics", "subcategory": "audio", "rating": 4.3, "in_stock": True, "trending": False, "description": "Audifonos premium con audio espacial y 40 horas de bateria"},
    {"product_id": "PROD-0028", "name": "Microfono Blue Yeti USB profesional", "price": 649000, "category": "electronics", "subcategory": "audio", "rating": 4.6, "in_stock": True, "trending": False, "description": "Microfono USB de estudio para streaming y podcasting"},
    {"product_id": "PROD-0029", "name": "Audifonos gamer HyperX Cloud III", "price": 449000, "category": "electronics", "subcategory": "audio", "rating": 4.4, "in_stock": True, "trending": False, "description": "Headset gamer con microfono y sonido envolvente DTS"},
    {"product_id": "PROD-0030", "name": "Parlante Marshall Stanmore II Bluetooth", "price": 1699000, "category": "electronics", "subcategory": "audio", "rating": 4.7, "in_stock": False, "trending": True, "description": "Parlante con diseno retro iconico y sonido Marshall potente"},
    # -- gaming --
    {"product_id": "PROD-0031", "name": "Consola PlayStation 5 Slim", "price": 2499000, "category": "electronics", "subcategory": "gaming", "rating": 4.8, "in_stock": True, "trending": True, "description": "Consola de nueva generacion con SSD ultrarapido y Ray Tracing"},
    {"product_id": "PROD-0032", "name": "Nintendo Switch OLED", "price": 1799000, "category": "electronics", "subcategory": "gaming", "rating": 4.7, "in_stock": True, "trending": True, "description": "Consola hibrida con pantalla OLED de 7 pulgadas vibrante"},
    {"product_id": "PROD-0033", "name": "Control DualSense PS5 edicion limitada", "price": 349000, "category": "electronics", "subcategory": "gaming", "rating": 4.5, "in_stock": True, "trending": False, "description": "Control inalambrico con retroalimentacion haptica avanzada"},
    {"product_id": "PROD-0034", "name": "Xbox Series S 512GB", "price": 1599000, "category": "electronics", "subcategory": "gaming", "rating": 4.4, "in_stock": True, "trending": False, "description": "Consola compacta con rendimiento de nueva generacion"},
    {"product_id": "PROD-0035", "name": "Silla gamer Cougar Armor One", "price": 899000, "category": "electronics", "subcategory": "gaming", "rating": 4.3, "in_stock": True, "trending": False, "description": "Silla gamer ergonomica con soporte lumbar ajustable"},
    {"product_id": "PROD-0036", "name": "Monitor gamer ASUS 27 pulgadas 165Hz", "price": 1299000, "category": "electronics", "subcategory": "gaming", "rating": 4.6, "in_stock": True, "trending": False, "description": "Monitor IPS con 1ms de respuesta ideal para gaming competitivo"},
    {"product_id": "PROD-0037", "name": "Teclado mecanico Razer Huntsman Mini", "price": 499000, "category": "electronics", "subcategory": "gaming", "rating": 4.5, "in_stock": True, "trending": False, "description": "Teclado compacto 60% con switches opticos ultrarapidos"},
    {"product_id": "PROD-0038", "name": "Mouse gamer Logitech G502 X", "price": 349000, "category": "electronics", "subcategory": "gaming", "rating": 4.7, "in_stock": True, "trending": False, "description": "Mouse gamer con sensor HERO 25K y 13 botones programables"},
    {"product_id": "PROD-0039", "name": "Headset gamer SteelSeries Arctis Nova 7", "price": 799000, "category": "electronics", "subcategory": "gaming", "rating": 4.4, "in_stock": True, "trending": False, "description": "Auriculares inalambricos con audio espacial 360 grados"},
    {"product_id": "PROD-0040", "name": "Tarjeta grafica NVIDIA RTX 4070 Super", "price": 3499000, "category": "electronics", "subcategory": "gaming", "rating": 4.8, "in_stock": False, "trending": True, "description": "GPU de alto rendimiento para gaming 4K y creacion de contenido"},
    # -- tablets --
    {"product_id": "PROD-0041", "name": "iPad Air M1 64GB", "price": 2799000, "category": "electronics", "subcategory": "tablets", "rating": 4.7, "in_stock": True, "trending": True, "description": "Tablet Apple con chip M1 y pantalla Liquid Retina de 10.9"},
    {"product_id": "PROD-0042", "name": "Samsung Galaxy Tab S9 FE", "price": 1699000, "category": "electronics", "subcategory": "tablets", "rating": 4.5, "in_stock": True, "trending": False, "description": "Tablet Samsung con S Pen incluido y resistencia al agua"},
    {"product_id": "PROD-0043", "name": "iPad 10ma generacion 64GB", "price": 1999000, "category": "electronics", "subcategory": "tablets", "rating": 4.6, "in_stock": True, "trending": False, "description": "iPad con chip A14 Bionic y USB-C para mayor versatilidad"},
    {"product_id": "PROD-0044", "name": "Lenovo Tab P12 128GB", "price": 1399000, "category": "electronics", "subcategory": "tablets", "rating": 4.3, "in_stock": True, "trending": False, "description": "Tablet con pantalla 2K de 12.7 pulgadas y Dolby Atmos"},
    {"product_id": "PROD-0045", "name": "Samsung Galaxy Tab A9 Plus", "price": 1099000, "category": "electronics", "subcategory": "tablets", "rating": 4.2, "in_stock": True, "trending": False, "description": "Tablet accesible con pantalla amplia ideal para entretenimiento"},
    {"product_id": "PROD-0046", "name": "Xiaomi Pad 6 128GB", "price": 1299000, "category": "electronics", "subcategory": "tablets", "rating": 4.4, "in_stock": True, "trending": False, "description": "Tablet con pantalla 144Hz y carga rapida de 33W incluida"},
    {"product_id": "PROD-0047", "name": "Apple Pencil 2da generacion", "price": 599000, "category": "electronics", "subcategory": "tablets", "rating": 4.6, "in_stock": True, "trending": False, "description": "Lapiz digital con carga magnetica y doble toque intuitivo"},
    {"product_id": "PROD-0048", "name": "Funda teclado Logitech para iPad", "price": 449000, "category": "electronics", "subcategory": "tablets", "rating": 4.3, "in_stock": True, "trending": False, "description": "Funda con teclado retroiluminado y trackpad integrado"},
    {"product_id": "PROD-0049", "name": "Huawei MatePad 11.5 pulgadas", "price": 1499000, "category": "electronics", "subcategory": "tablets", "rating": 4.1, "in_stock": True, "trending": False, "description": "Tablet con pantalla 120Hz y soporte para lapiz optico"},
    {"product_id": "PROD-0050", "name": "Amazon Fire HD 10 2023", "price": 699000, "category": "electronics", "subcategory": "tablets", "rating": 3.9, "in_stock": False, "trending": False, "description": "Tablet economica con Alexa integrada y 12 horas de bateria"},
    # -- wearables --
    {"product_id": "PROD-0051", "name": "Apple Watch Series 9 45mm", "price": 2199000, "category": "electronics", "subcategory": "wearables", "rating": 4.7, "in_stock": True, "trending": True, "description": "Reloj inteligente con deteccion de gestos y pantalla brillante"},
    {"product_id": "PROD-0052", "name": "Samsung Galaxy Watch6 Classic", "price": 1599000, "category": "electronics", "subcategory": "wearables", "rating": 4.5, "in_stock": True, "trending": False, "description": "Smartwatch con bisel giratorio clasico y monitoreo de salud"},
    {"product_id": "PROD-0053", "name": "Garmin Venu 3S", "price": 1899000, "category": "electronics", "subcategory": "wearables", "rating": 4.6, "in_stock": True, "trending": False, "description": "Reloj GPS con monitoreo avanzado de sueno y asistente de voz"},
    {"product_id": "PROD-0054", "name": "Xiaomi Smart Band 8", "price": 149000, "category": "electronics", "subcategory": "wearables", "rating": 4.3, "in_stock": True, "trending": False, "description": "Banda inteligente economica con 150 modos deportivos"},
    {"product_id": "PROD-0055", "name": "Fitbit Charge 6", "price": 699000, "category": "electronics", "subcategory": "wearables", "rating": 4.2, "in_stock": True, "trending": False, "description": "Tracker de fitness con GPS integrado y Google Maps"},
    {"product_id": "PROD-0056", "name": "Amazfit GTR 4", "price": 899000, "category": "electronics", "subcategory": "wearables", "rating": 4.4, "in_stock": True, "trending": False, "description": "Smartwatch deportivo con 14 dias de bateria y GPS dual"},
    {"product_id": "PROD-0057", "name": "Apple Watch SE 2da generacion", "price": 1299000, "category": "electronics", "subcategory": "wearables", "rating": 4.5, "in_stock": True, "trending": False, "description": "Apple Watch accesible con deteccion de choques y caidas"},
    {"product_id": "PROD-0058", "name": "Huawei Watch GT 4 46mm", "price": 999000, "category": "electronics", "subcategory": "wearables", "rating": 4.3, "in_stock": True, "trending": False, "description": "Reloj elegante con 14 dias de bateria y monitoreo cardiaco"},
    {"product_id": "PROD-0059", "name": "Samsung Galaxy Fit3", "price": 249000, "category": "electronics", "subcategory": "wearables", "rating": 4.1, "in_stock": True, "trending": False, "description": "Banda fitness ligera con pantalla AMOLED y resistencia al agua"},
    {"product_id": "PROD-0060", "name": "Garmin Forerunner 265", "price": 2099000, "category": "electronics", "subcategory": "wearables", "rating": 4.7, "in_stock": False, "trending": True, "description": "Reloj GPS para corredores con pantalla AMOLED y metricas"},
    # -- cameras --
    {"product_id": "PROD-0061", "name": "Camara Canon EOS R50 con lente 18-45mm", "price": 4299000, "category": "electronics", "subcategory": "cameras", "rating": 4.6, "in_stock": True, "trending": True, "description": "Camara mirrorless compacta con video 4K y enfoque automatico"},
    {"product_id": "PROD-0062", "name": "GoPro HERO12 Black", "price": 2099000, "category": "electronics", "subcategory": "cameras", "rating": 4.5, "in_stock": True, "trending": True, "description": "Camara de accion con estabilizacion HyperSmooth 6.0"},
    {"product_id": "PROD-0063", "name": "Camara Sony Alpha a6400 cuerpo", "price": 3999000, "category": "electronics", "subcategory": "cameras", "rating": 4.7, "in_stock": True, "trending": False, "description": "Mirrorless con enfoque automatico rapido y video 4K HDR"},
    {"product_id": "PROD-0064", "name": "Instax Mini 12 Fujifilm", "price": 349000, "category": "electronics", "subcategory": "cameras", "rating": 4.4, "in_stock": True, "trending": False, "description": "Camara instantanea compacta con exposicion automatica"},
    {"product_id": "PROD-0065", "name": "DJI Mini 3 Drone con camara", "price": 2999000, "category": "electronics", "subcategory": "cameras", "rating": 4.6, "in_stock": True, "trending": False, "description": "Drone ultraligero con camara 4K y 38 minutos de vuelo"},
    {"product_id": "PROD-0066", "name": "Camara Nikon Z30 con lente 16-50mm", "price": 3799000, "category": "electronics", "subcategory": "cameras", "rating": 4.5, "in_stock": True, "trending": False, "description": "Camara mirrorless ideal para vlogging con pantalla abatible"},
    {"product_id": "PROD-0067", "name": "Ring Indoor Cam 2da generacion", "price": 249000, "category": "electronics", "subcategory": "cameras", "rating": 4.2, "in_stock": True, "trending": False, "description": "Camara de seguridad interior con vision nocturna y WiFi"},
    {"product_id": "PROD-0068", "name": "Webcam Logitech C920 HD Pro", "price": 349000, "category": "electronics", "subcategory": "cameras", "rating": 4.5, "in_stock": True, "trending": False, "description": "Webcam Full HD 1080p ideal para videollamadas profesionales"},
    {"product_id": "PROD-0069", "name": "DJI Osmo Action 4", "price": 1599000, "category": "electronics", "subcategory": "cameras", "rating": 4.4, "in_stock": True, "trending": False, "description": "Camara de accion con sensor grande y pantalla dual tactil"},
    {"product_id": "PROD-0070", "name": "Camara Panasonic Lumix G7 4K", "price": 2899000, "category": "electronics", "subcategory": "cameras", "rating": 4.3, "in_stock": False, "trending": False, "description": "Camara micro cuatro tercios con video 4K y visor electronico"},
    # -- accessories --
    {"product_id": "PROD-0071", "name": "Cargador inalambrico Samsung 15W", "price": 149000, "category": "electronics", "subcategory": "accessories", "rating": 4.3, "in_stock": True, "trending": False, "description": "Cargador inalambrico rapido compatible con Qi universal"},
    {"product_id": "PROD-0072", "name": "Power bank Anker 20000mAh", "price": 179000, "category": "electronics", "subcategory": "accessories", "rating": 4.6, "in_stock": True, "trending": False, "description": "Bateria externa con carga rapida y doble puerto USB-C"},
    {"product_id": "PROD-0073", "name": "Cable USB-C Belkin trenzado 2m", "price": 79000, "category": "electronics", "subcategory": "accessories", "rating": 4.4, "in_stock": True, "trending": False, "description": "Cable USB-C reforzado con trenzado de nylon resistente"},
    {"product_id": "PROD-0074", "name": "Soporte de laptop ajustable aluminio", "price": 129000, "category": "electronics", "subcategory": "accessories", "rating": 4.5, "in_stock": True, "trending": False, "description": "Soporte ergonomico de aluminio con ventilacion para portatil"},
    {"product_id": "PROD-0075", "name": "Hub USB-C 7 en 1 Ugreen", "price": 199000, "category": "electronics", "subcategory": "accessories", "rating": 4.4, "in_stock": True, "trending": False, "description": "Hub multipuerto con HDMI 4K y lector de tarjetas integrado"},
    {"product_id": "PROD-0076", "name": "Protector de pantalla iPhone 15 Pro", "price": 49000, "category": "electronics", "subcategory": "accessories", "rating": 4.2, "in_stock": True, "trending": False, "description": "Vidrio templado 9H con instalacion facil y anti-huellas"},
    {"product_id": "PROD-0077", "name": "Funda protectora Samsung Galaxy S24", "price": 89000, "category": "electronics", "subcategory": "accessories", "rating": 4.1, "in_stock": True, "trending": False, "description": "Funda transparente antigolpes con bordes reforzados"},
    {"product_id": "PROD-0078", "name": "Memoria USB SanDisk 128GB", "price": 59000, "category": "electronics", "subcategory": "accessories", "rating": 4.5, "in_stock": True, "trending": False, "description": "Memoria USB 3.0 compacta con velocidad de lectura de 130MB/s"},
    {"product_id": "PROD-0079", "name": "Disco duro externo Seagate 2TB", "price": 299000, "category": "electronics", "subcategory": "accessories", "rating": 4.4, "in_stock": True, "trending": False, "description": "Disco duro portatil USB 3.0 para respaldo de archivos"},
    {"product_id": "PROD-0080", "name": "Tarjeta microSD Samsung 256GB", "price": 139000, "category": "electronics", "subcategory": "accessories", "rating": 4.5, "in_stock": False, "trending": False, "description": "Tarjeta de memoria de alta velocidad para celulares y camaras"},
    # ===================================================================
    # HOME (~80 products) - PROD-0081 to PROD-0160
    # ===================================================================
    # -- kitchen --
    {"product_id": "PROD-0081", "name": "Olla a presion Imusa 6 litros", "price": 189000, "category": "home", "subcategory": "kitchen", "rating": 4.5, "in_stock": True, "trending": False, "description": "Olla a presion de aluminio con sistema de seguridad triple"},
    {"product_id": "PROD-0082", "name": "Licuadora Oster Pro 1200W", "price": 299000, "category": "home", "subcategory": "kitchen", "rating": 4.4, "in_stock": True, "trending": False, "description": "Licuadora de alto rendimiento con vaso de vidrio resistente"},
    {"product_id": "PROD-0083", "name": "Juego de cuchillos Tramontina 6 piezas", "price": 149000, "category": "home", "subcategory": "kitchen", "rating": 4.6, "in_stock": True, "trending": False, "description": "Set de cuchillos de acero inoxidable con bloque de madera"},
    {"product_id": "PROD-0084", "name": "Freidora de aire Ninja 5.5 litros", "price": 449000, "category": "home", "subcategory": "kitchen", "rating": 4.7, "in_stock": True, "trending": True, "description": "Freidora de aire con 6 funciones y canasta antiadherente"},
    {"product_id": "PROD-0085", "name": "Cafetera De'Longhi Magnifica S", "price": 1899000, "category": "home", "subcategory": "kitchen", "rating": 4.8, "in_stock": True, "trending": True, "description": "Cafetera automatica con molinillo integrado y espumador"},
    {"product_id": "PROD-0086", "name": "Set de ollas antiadherentes T-fal 10 piezas", "price": 449000, "category": "home", "subcategory": "kitchen", "rating": 4.5, "in_stock": True, "trending": False, "description": "Juego de ollas y sartenes con indicador de calor Thermo-Spot"},
    {"product_id": "PROD-0087", "name": "Horno microondas Samsung 32 litros", "price": 399000, "category": "home", "subcategory": "kitchen", "rating": 4.3, "in_stock": True, "trending": False, "description": "Microondas con tecnologia ceramica interior y grill"},
    {"product_id": "PROD-0088", "name": "Procesador de alimentos KitchenAid 13 tazas", "price": 899000, "category": "home", "subcategory": "kitchen", "rating": 4.6, "in_stock": True, "trending": False, "description": "Procesador potente con multiples cuchillas y accesorios"},
    {"product_id": "PROD-0089", "name": "Sanduchera Oster doble", "price": 129000, "category": "home", "subcategory": "kitchen", "rating": 4.2, "in_stock": True, "trending": False, "description": "Sanduchera con placas antiadherentes y cierre de seguridad"},
    {"product_id": "PROD-0090", "name": "Tabla de cortar bambu premium grande", "price": 79000, "category": "home", "subcategory": "kitchen", "rating": 4.4, "in_stock": True, "trending": False, "description": "Tabla de cortar ecologica de bambu con canal para jugos"},
    # -- furniture --
    {"product_id": "PROD-0091", "name": "Escritorio de madera ajustable en altura", "price": 899000, "category": "home", "subcategory": "furniture", "rating": 4.5, "in_stock": True, "trending": True, "description": "Escritorio ergonomico con ajuste electrico de altura"},
    {"product_id": "PROD-0092", "name": "Silla ergonomica de oficina con soporte lumbar", "price": 799000, "category": "home", "subcategory": "furniture", "rating": 4.6, "in_stock": True, "trending": True, "description": "Silla de oficina con malla transpirable y reposabrazos 3D"},
    {"product_id": "PROD-0093", "name": "Sofa cama 3 puestos tela gris", "price": 1599000, "category": "home", "subcategory": "furniture", "rating": 4.4, "in_stock": True, "trending": False, "description": "Sofa convertible con almacenamiento interno y tela lavable"},
    {"product_id": "PROD-0094", "name": "Mesa de comedor extensible 6 puestos", "price": 1299000, "category": "home", "subcategory": "furniture", "rating": 4.3, "in_stock": True, "trending": False, "description": "Mesa de comedor en madera natural con extension para 8"},
    {"product_id": "PROD-0095", "name": "Estanteria modular 5 niveles roble", "price": 449000, "category": "home", "subcategory": "furniture", "rating": 4.5, "in_stock": True, "trending": False, "description": "Estanteria de madera con acabado roble y estructura metalica"},
    {"product_id": "PROD-0096", "name": "Cama doble con cabecero tapizado", "price": 1899000, "category": "home", "subcategory": "furniture", "rating": 4.4, "in_stock": True, "trending": False, "description": "Cama con cabecero acolchado en tela y estructura reforzada"},
    {"product_id": "PROD-0097", "name": "Mesa de centro moderna con vidrio", "price": 399000, "category": "home", "subcategory": "furniture", "rating": 4.2, "in_stock": True, "trending": False, "description": "Mesa de centro con tapa de vidrio templado y base metalica"},
    {"product_id": "PROD-0098", "name": "Mueble de TV flotante 160cm", "price": 599000, "category": "home", "subcategory": "furniture", "rating": 4.5, "in_stock": True, "trending": False, "description": "Mueble flotante para TV con compartimentos y pasacables"},
    {"product_id": "PROD-0099", "name": "Sillon reclinable de cuero sintetico", "price": 999000, "category": "home", "subcategory": "furniture", "rating": 4.3, "in_stock": False, "trending": False, "description": "Sillon reclinable con reposapies y portavasos integrados"},
    {"product_id": "PROD-0100", "name": "Puf redondo grande terciopelo verde", "price": 249000, "category": "home", "subcategory": "furniture", "rating": 4.1, "in_stock": True, "trending": False, "description": "Puf decorativo de terciopelo con relleno de microperlas"},
    # -- decor --
    {"product_id": "PROD-0101", "name": "Cuadro decorativo abstracto 80x60cm", "price": 189000, "category": "home", "subcategory": "decor", "rating": 4.3, "in_stock": True, "trending": False, "description": "Cuadro de arte abstracto impreso en canvas con marco"},
    {"product_id": "PROD-0102", "name": "Espejo redondo con marco dorado 70cm", "price": 299000, "category": "home", "subcategory": "decor", "rating": 4.5, "in_stock": True, "trending": True, "description": "Espejo decorativo con marco metalico dorado estilo moderno"},
    {"product_id": "PROD-0103", "name": "Set de 3 macetas de ceramica decorativas", "price": 129000, "category": "home", "subcategory": "decor", "rating": 4.4, "in_stock": True, "trending": False, "description": "Macetas decorativas en ceramica con bandeja de drenaje"},
    {"product_id": "PROD-0104", "name": "Cortinas blackout gris 200x230cm", "price": 179000, "category": "home", "subcategory": "decor", "rating": 4.6, "in_stock": True, "trending": False, "description": "Cortinas opacas con aislamiento termico y proteccion UV"},
    {"product_id": "PROD-0105", "name": "Tapete persa moderno 160x230cm", "price": 449000, "category": "home", "subcategory": "decor", "rating": 4.4, "in_stock": True, "trending": False, "description": "Tapete con diseno persa contemporaneo y pelo corto suave"},
    {"product_id": "PROD-0106", "name": "Reloj de pared minimalista madera", "price": 119000, "category": "home", "subcategory": "decor", "rating": 4.2, "in_stock": True, "trending": False, "description": "Reloj de pared silencioso con marco de madera natural"},
    {"product_id": "PROD-0107", "name": "Jarron de cristal soplado artesanal", "price": 149000, "category": "home", "subcategory": "decor", "rating": 4.3, "in_stock": True, "trending": False, "description": "Jarron artesanal de cristal soplado a mano con colores unicos"},
    {"product_id": "PROD-0108", "name": "Set de cojines decorativos 4 piezas", "price": 159000, "category": "home", "subcategory": "decor", "rating": 4.5, "in_stock": True, "trending": False, "description": "Cojines decorativos con fundas lavables en tonos neutros"},
    {"product_id": "PROD-0109", "name": "Vela aromatica de soya lavanda 300g", "price": 69000, "category": "home", "subcategory": "decor", "rating": 4.6, "in_stock": True, "trending": False, "description": "Vela artesanal de cera de soya con aroma natural de lavanda"},
    {"product_id": "PROD-0110", "name": "Planta artificial monstera 120cm", "price": 199000, "category": "home", "subcategory": "decor", "rating": 4.1, "in_stock": False, "trending": False, "description": "Planta decorativa artificial de aspecto realista con maceta"},
    # -- cleaning --
    {"product_id": "PROD-0111", "name": "Aspiradora robot iRobot Roomba i3+", "price": 1799000, "category": "home", "subcategory": "cleaning", "rating": 4.6, "in_stock": True, "trending": True, "description": "Robot aspirador con autovaciado y navegacion inteligente"},
    {"product_id": "PROD-0112", "name": "Aspiradora vertical Dyson V12 Detect", "price": 2499000, "category": "home", "subcategory": "cleaning", "rating": 4.7, "in_stock": True, "trending": True, "description": "Aspiradora inalambrica con laser para detectar particulas"},
    {"product_id": "PROD-0113", "name": "Trapeadora a vapor Shark S3501", "price": 499000, "category": "home", "subcategory": "cleaning", "rating": 4.4, "in_stock": True, "trending": False, "description": "Limpiador a vapor que sanitiza pisos sin quimicos"},
    {"product_id": "PROD-0114", "name": "Detergente liquido Ariel 5 litros", "price": 59000, "category": "home", "subcategory": "cleaning", "rating": 4.5, "in_stock": True, "trending": False, "description": "Detergente concentrado con poder quitamanchas avanzado"},
    {"product_id": "PROD-0115", "name": "Organizador de limpieza con ruedas", "price": 89000, "category": "home", "subcategory": "cleaning", "rating": 4.2, "in_stock": True, "trending": False, "description": "Carro organizador con ruedas para productos de limpieza"},
    {"product_id": "PROD-0116", "name": "Escoba electrica Karcher S 650", "price": 349000, "category": "home", "subcategory": "cleaning", "rating": 4.3, "in_stock": True, "trending": False, "description": "Escoba electrica sin cables para limpieza rapida de pisos"},
    {"product_id": "PROD-0117", "name": "Set de microfibra limpieza 12 panos", "price": 39000, "category": "home", "subcategory": "cleaning", "rating": 4.4, "in_stock": True, "trending": False, "description": "Panos de microfibra multiuso de alta absorcion y durabilidad"},
    {"product_id": "PROD-0118", "name": "Balde con escurridor giratorio", "price": 69000, "category": "home", "subcategory": "cleaning", "rating": 4.3, "in_stock": True, "trending": False, "description": "Sistema de limpieza con escurridor centrifugo y pedal"},
    {"product_id": "PROD-0119", "name": "Purificador de aire Philips AC1215", "price": 799000, "category": "home", "subcategory": "cleaning", "rating": 4.5, "in_stock": True, "trending": False, "description": "Purificador con filtro HEPA que elimina 99.97% de particulas"},
    {"product_id": "PROD-0120", "name": "Humidificador ultrasonico 3 litros", "price": 179000, "category": "home", "subcategory": "cleaning", "rating": 4.2, "in_stock": False, "trending": False, "description": "Humidificador silencioso con luz LED y apagado automatico"},
    # -- garden --
    {"product_id": "PROD-0121", "name": "Kit de herramientas de jardin 10 piezas", "price": 129000, "category": "home", "subcategory": "garden", "rating": 4.4, "in_stock": True, "trending": False, "description": "Set completo de herramientas con mangos ergonomicos"},
    {"product_id": "PROD-0122", "name": "Manguera expandible 30 metros", "price": 99000, "category": "home", "subcategory": "garden", "rating": 4.3, "in_stock": True, "trending": False, "description": "Manguera flexible con 8 modos de riego y conector universal"},
    {"product_id": "PROD-0123", "name": "Maceta inteligente con autorriego", "price": 149000, "category": "home", "subcategory": "garden", "rating": 4.5, "in_stock": True, "trending": True, "description": "Maceta con sistema de riego automatico y sensor de humedad"},
    {"product_id": "PROD-0124", "name": "Set de sustratos y fertilizantes organicos", "price": 89000, "category": "home", "subcategory": "garden", "rating": 4.4, "in_stock": True, "trending": False, "description": "Kit de tierra y nutrientes organicos para plantas de interior"},
    {"product_id": "PROD-0125", "name": "Podadora electrica Black+Decker", "price": 299000, "category": "home", "subcategory": "garden", "rating": 4.3, "in_stock": True, "trending": False, "description": "Podadora electrica liviana con 40cm de corte ajustable"},
    {"product_id": "PROD-0126", "name": "Farol solar jardin LED pack de 6", "price": 119000, "category": "home", "subcategory": "garden", "rating": 4.2, "in_stock": True, "trending": False, "description": "Faroles solares decorativos con encendido automatico nocturno"},
    {"product_id": "PROD-0127", "name": "Hamaca doble de algodon con soporte", "price": 399000, "category": "home", "subcategory": "garden", "rating": 4.6, "in_stock": True, "trending": False, "description": "Hamaca doble con estructura metalica resistente a la intemperie"},
    {"product_id": "PROD-0128", "name": "Juego de muebles de terraza ratan 4 piezas", "price": 1499000, "category": "home", "subcategory": "garden", "rating": 4.5, "in_stock": True, "trending": False, "description": "Set de terraza con sofa, sillones y mesa de ratan sintetico"},
    {"product_id": "PROD-0129", "name": "Parrilla a carbon portatil acero inoxidable", "price": 249000, "category": "home", "subcategory": "garden", "rating": 4.4, "in_stock": True, "trending": False, "description": "Parrilla plegable de acero inoxidable con regulador de aire"},
    {"product_id": "PROD-0130", "name": "Compostera domestica 80 litros", "price": 179000, "category": "home", "subcategory": "garden", "rating": 4.1, "in_stock": False, "trending": False, "description": "Compostera para residuos organicos con sistema de ventilacion"},
    # -- lighting --
    {"product_id": "PROD-0131", "name": "Lampara de pie inteligente Philips Hue", "price": 379000, "category": "home", "subcategory": "lighting", "rating": 4.6, "in_stock": True, "trending": True, "description": "Lampara inteligente con 16 millones de colores y control por app"},
    {"product_id": "PROD-0132", "name": "Tira LED RGB 10 metros con control remoto", "price": 89000, "category": "home", "subcategory": "lighting", "rating": 4.3, "in_stock": True, "trending": True, "description": "Tira LED multicolor con modos de escena y sincronizacion musical"},
    {"product_id": "PROD-0133", "name": "Lampara de escritorio LED con carga inalambrica", "price": 199000, "category": "home", "subcategory": "lighting", "rating": 4.5, "in_stock": True, "trending": False, "description": "Lampara con base de carga Qi y 5 niveles de brillo ajustable"},
    {"product_id": "PROD-0134", "name": "Bombillo inteligente WiFi pack de 4", "price": 149000, "category": "home", "subcategory": "lighting", "rating": 4.4, "in_stock": True, "trending": False, "description": "Bombillos inteligentes compatibles con Alexa y Google Home"},
    {"product_id": "PROD-0135", "name": "Lampara colgante industrial vintage", "price": 229000, "category": "home", "subcategory": "lighting", "rating": 4.3, "in_stock": True, "trending": False, "description": "Lampara colgante estilo industrial con acabado en negro mate"},
    {"product_id": "PROD-0136", "name": "Aplique de pared moderno doble luz", "price": 159000, "category": "home", "subcategory": "lighting", "rating": 4.2, "in_stock": True, "trending": False, "description": "Aplique de pared con haz de luz superior e inferior ajustable"},
    {"product_id": "PROD-0137", "name": "Guirnalda de luces decorativa 5 metros", "price": 49000, "category": "home", "subcategory": "lighting", "rating": 4.5, "in_stock": True, "trending": False, "description": "Guirnalda de luces calidas ideal para decoracion de interiores"},
    {"product_id": "PROD-0138", "name": "Lampara de mesa de noche tactil", "price": 119000, "category": "home", "subcategory": "lighting", "rating": 4.4, "in_stock": True, "trending": False, "description": "Lampara de noche con control tactil y tres intensidades"},
    {"product_id": "PROD-0139", "name": "Panel LED empotrable slim 24W", "price": 79000, "category": "home", "subcategory": "lighting", "rating": 4.3, "in_stock": True, "trending": False, "description": "Panel LED ultradelgado de luz blanca neutra para cielo raso"},
    {"product_id": "PROD-0140", "name": "Sensor de movimiento con luz LED", "price": 59000, "category": "home", "subcategory": "lighting", "rating": 4.1, "in_stock": False, "trending": False, "description": "Luz automatica con sensor de movimiento para pasillos y closets"},
    # -- storage --
    {"product_id": "PROD-0141", "name": "Organizador de closet modular 6 cubos", "price": 189000, "category": "home", "subcategory": "storage", "rating": 4.4, "in_stock": True, "trending": False, "description": "Sistema modular de cubos con puertas para organizar ropa"},
    {"product_id": "PROD-0142", "name": "Cajas de almacenamiento apilables pack 3", "price": 99000, "category": "home", "subcategory": "storage", "rating": 4.3, "in_stock": True, "trending": False, "description": "Cajas plasticas transparentes con tapa hermetica apilable"},
    {"product_id": "PROD-0143", "name": "Zapatera de 10 niveles con funda", "price": 129000, "category": "home", "subcategory": "storage", "rating": 4.2, "in_stock": True, "trending": False, "description": "Zapatera con funda de tela protectora para 30 pares"},
    {"product_id": "PROD-0144", "name": "Organizador de bano acero inoxidable 3 niveles", "price": 149000, "category": "home", "subcategory": "storage", "rating": 4.5, "in_stock": True, "trending": False, "description": "Estante de bano resistente a la humedad con ventosas fuertes"},
    {"product_id": "PROD-0145", "name": "Cesta de ropa bambu con tapa", "price": 109000, "category": "home", "subcategory": "storage", "rating": 4.4, "in_stock": True, "trending": False, "description": "Cesta de ropa sucia de bambu natural con bolsa interior lavable"},
    {"product_id": "PROD-0146", "name": "Organizador de escritorio giratorio", "price": 79000, "category": "home", "subcategory": "storage", "rating": 4.3, "in_stock": True, "trending": False, "description": "Organizador giratorio 360 grados para utiles de escritorio"},
    {"product_id": "PROD-0147", "name": "Perchero de pie metalico estilo nordico", "price": 169000, "category": "home", "subcategory": "storage", "rating": 4.2, "in_stock": True, "trending": False, "description": "Perchero de pie con 8 ganchos y base estable antideslizante"},
    {"product_id": "PROD-0148", "name": "Set de frascos hermeticos vidrio 5 piezas", "price": 89000, "category": "home", "subcategory": "storage", "rating": 4.5, "in_stock": True, "trending": False, "description": "Frascos de vidrio con tapa hermetica de bambu para cocina"},
    {"product_id": "PROD-0149", "name": "Mueble organizador multiusos con ruedas", "price": 219000, "category": "home", "subcategory": "storage", "rating": 4.3, "in_stock": True, "trending": False, "description": "Mueble de 4 niveles con ruedas para cocina o bano"},
    {"product_id": "PROD-0150", "name": "Bolsas al vacio para ropa pack 10", "price": 49000, "category": "home", "subcategory": "storage", "rating": 4.1, "in_stock": False, "trending": False, "description": "Bolsas selladas al vacio para ahorrar espacio en el closet"},
    # -- bedding --
    {"product_id": "PROD-0151", "name": "Juego de sabanas 100% algodon egipcio", "price": 299000, "category": "home", "subcategory": "bedding", "rating": 4.7, "in_stock": True, "trending": True, "description": "Sabanas de 600 hilos con acabado suave y duradero premium"},
    {"product_id": "PROD-0152", "name": "Edredon de plumas sinteticas king", "price": 399000, "category": "home", "subcategory": "bedding", "rating": 4.5, "in_stock": True, "trending": False, "description": "Edredon hipoalergenico con relleno de fibra sintetica premium"},
    {"product_id": "PROD-0153", "name": "Almohada viscoelastica cervical", "price": 149000, "category": "home", "subcategory": "bedding", "rating": 4.6, "in_stock": True, "trending": False, "description": "Almohada de memory foam con soporte cervical anatomico"},
    {"product_id": "PROD-0154", "name": "Protector de colchon impermeable queen", "price": 119000, "category": "home", "subcategory": "bedding", "rating": 4.4, "in_stock": True, "trending": False, "description": "Protector impermeable transpirable con ajuste elastico"},
    {"product_id": "PROD-0155", "name": "Cobija de flanela premium 200x220cm", "price": 179000, "category": "home", "subcategory": "bedding", "rating": 4.5, "in_stock": True, "trending": False, "description": "Cobija de flanela ultrasuave con diseno elegante y calida"},
    {"product_id": "PROD-0156", "name": "Colchon memory foam 140x190cm", "price": 1299000, "category": "home", "subcategory": "bedding", "rating": 4.7, "in_stock": True, "trending": True, "description": "Colchon de espuma viscoelastica con 7 zonas de soporte"},
    {"product_id": "PROD-0157", "name": "Set de toallas premium 6 piezas", "price": 189000, "category": "home", "subcategory": "bedding", "rating": 4.4, "in_stock": True, "trending": False, "description": "Toallas de algodon turco 600gsm ultraabsorbentes y suaves"},
    {"product_id": "PROD-0158", "name": "Almohada de cuerpo entero embarazo", "price": 139000, "category": "home", "subcategory": "bedding", "rating": 4.3, "in_stock": True, "trending": False, "description": "Almohada en forma de U para soporte total durante el embarazo"},
    {"product_id": "PROD-0159", "name": "Funda nordica estampada 200x200cm", "price": 219000, "category": "home", "subcategory": "bedding", "rating": 4.2, "in_stock": True, "trending": False, "description": "Funda nordica de microfibra con cierre oculto y estampado"},
    {"product_id": "PROD-0160", "name": "Cubrecolchon de bambu king size", "price": 249000, "category": "home", "subcategory": "bedding", "rating": 4.5, "in_stock": False, "trending": False, "description": "Cubrecolchon termorregulador de fibra de bambu hipoalergenico"},
    # ===================================================================
    # FASHION (~70 products) - PROD-0161 to PROD-0230
    # ===================================================================
    # -- women_clothing --
    {"product_id": "PROD-0161", "name": "Vestido largo floral manga larga", "price": 189000, "category": "fashion", "subcategory": "women_clothing", "rating": 4.4, "in_stock": True, "trending": True, "description": "Vestido elegante con estampado floral y tela fluida ligera"},
    {"product_id": "PROD-0162", "name": "Blusa de seda natural cuello V", "price": 149000, "category": "fashion", "subcategory": "women_clothing", "rating": 4.3, "in_stock": True, "trending": False, "description": "Blusa de seda con caida perfecta ideal para oficina o salidas"},
    {"product_id": "PROD-0163", "name": "Pantalon palazzo tela fluida negro", "price": 129000, "category": "fashion", "subcategory": "women_clothing", "rating": 4.5, "in_stock": True, "trending": False, "description": "Pantalon palazzo de talle alto con cintura elastica comoda"},
    {"product_id": "PROD-0164", "name": "Chaqueta de jean oversize azul claro", "price": 179000, "category": "fashion", "subcategory": "women_clothing", "rating": 4.4, "in_stock": True, "trending": True, "description": "Chaqueta de denim oversize con bolsillos y botones metalicos"},
    {"product_id": "PROD-0165", "name": "Falda midi plisada elegante", "price": 119000, "category": "fashion", "subcategory": "women_clothing", "rating": 4.2, "in_stock": True, "trending": False, "description": "Falda midi plisada con cintura elastica en tonos neutros"},
    {"product_id": "PROD-0166", "name": "Conjunto deportivo leggings y top", "price": 159000, "category": "fashion", "subcategory": "women_clothing", "rating": 4.5, "in_stock": True, "trending": False, "description": "Set deportivo de dos piezas con tela de compresion suave"},
    {"product_id": "PROD-0167", "name": "Vestido de fiesta corto lentejuelas", "price": 259000, "category": "fashion", "subcategory": "women_clothing", "rating": 4.3, "in_stock": True, "trending": False, "description": "Vestido de fiesta con lentejuelas y escote en espalda"},
    {"product_id": "PROD-0168", "name": "Cardigan largo tejido punto grueso", "price": 139000, "category": "fashion", "subcategory": "women_clothing", "rating": 4.4, "in_stock": True, "trending": False, "description": "Cardigan oversize de punto grueso perfecto para dias frios"},
    {"product_id": "PROD-0169", "name": "Body manga larga cuello alto negro", "price": 79000, "category": "fashion", "subcategory": "women_clothing", "rating": 4.2, "in_stock": True, "trending": False, "description": "Body basico de algodon con cuello alto y cierre inferior"},
    {"product_id": "PROD-0170", "name": "Jumpsuit elegante escote cruzado", "price": 199000, "category": "fashion", "subcategory": "women_clothing", "rating": 4.3, "in_stock": False, "trending": False, "description": "Jumpsuit de una pieza con escote cruzado y cinturon incluido"},
    # -- men_clothing --
    {"product_id": "PROD-0171", "name": "Camisa formal slim fit algodon", "price": 129000, "category": "fashion", "subcategory": "men_clothing", "rating": 4.4, "in_stock": True, "trending": False, "description": "Camisa de algodon con corte slim fit y cuello italiano"},
    {"product_id": "PROD-0172", "name": "Jean skinny stretch azul oscuro", "price": 149000, "category": "fashion", "subcategory": "men_clothing", "rating": 4.5, "in_stock": True, "trending": True, "description": "Jean elastico con ajuste perfecto y lavado oscuro clasico"},
    {"product_id": "PROD-0173", "name": "Chaqueta de cuero sintetico negra", "price": 299000, "category": "fashion", "subcategory": "men_clothing", "rating": 4.3, "in_stock": True, "trending": False, "description": "Chaqueta estilo biker en cuero sintetico con forro interior"},
    {"product_id": "PROD-0174", "name": "Polo basico algodon pique", "price": 89000, "category": "fashion", "subcategory": "men_clothing", "rating": 4.4, "in_stock": True, "trending": False, "description": "Polo clasico de algodon pique con bordado en pecho"},
    {"product_id": "PROD-0175", "name": "Pantalon chino slim beige", "price": 119000, "category": "fashion", "subcategory": "men_clothing", "rating": 4.3, "in_stock": True, "trending": False, "description": "Pantalon chino de algodon con corte slim y bolsillos"},
    {"product_id": "PROD-0176", "name": "Sudadera con capucha algodon organico", "price": 139000, "category": "fashion", "subcategory": "men_clothing", "rating": 4.5, "in_stock": True, "trending": True, "description": "Hoodie de algodon organico con bolsillo canguro y capucha"},
    {"product_id": "PROD-0177", "name": "Blazer casual de lino azul marino", "price": 249000, "category": "fashion", "subcategory": "men_clothing", "rating": 4.2, "in_stock": True, "trending": False, "description": "Blazer de lino liviano ideal para eventos semi-formales"},
    {"product_id": "PROD-0178", "name": "Bermuda cargo algodon verde militar", "price": 99000, "category": "fashion", "subcategory": "men_clothing", "rating": 4.3, "in_stock": True, "trending": False, "description": "Bermuda cargo con bolsillos laterales y cinturon incluido"},
    {"product_id": "PROD-0179", "name": "Camiseta estampada algodon premium", "price": 69000, "category": "fashion", "subcategory": "men_clothing", "rating": 4.4, "in_stock": True, "trending": False, "description": "Camiseta de algodon 100% con estampado original y suave"},
    {"product_id": "PROD-0180", "name": "Traje formal 2 piezas slim fit", "price": 599000, "category": "fashion", "subcategory": "men_clothing", "rating": 4.5, "in_stock": False, "trending": False, "description": "Traje de dos piezas con saco y pantalon en tela premium"},
    # -- shoes --
    {"product_id": "PROD-0181", "name": "Zapatillas Nike Air Max 90", "price": 549000, "category": "fashion", "subcategory": "shoes", "rating": 4.7, "in_stock": True, "trending": True, "description": "Zapatillas iconicas con camara de aire visible y amortiguacion"},
    {"product_id": "PROD-0182", "name": "Botas de cuero Chelsea marrones", "price": 349000, "category": "fashion", "subcategory": "shoes", "rating": 4.4, "in_stock": True, "trending": False, "description": "Botas Chelsea de cuero genuino con elastico lateral"},
    {"product_id": "PROD-0183", "name": "Sandalias plataforma verano doradas", "price": 159000, "category": "fashion", "subcategory": "shoes", "rating": 4.3, "in_stock": True, "trending": False, "description": "Sandalias con plataforma comoda y acabado metalico dorado"},
    {"product_id": "PROD-0184", "name": "Tenis Adidas Ultraboost 22", "price": 699000, "category": "fashion", "subcategory": "shoes", "rating": 4.6, "in_stock": True, "trending": True, "description": "Zapatillas de running con tecnologia Boost de maxima energia"},
    {"product_id": "PROD-0185", "name": "Zapatos formales de cuero negro", "price": 289000, "category": "fashion", "subcategory": "shoes", "rating": 4.4, "in_stock": True, "trending": False, "description": "Zapatos clasicos de cuero con suela de goma antideslizante"},
    {"product_id": "PROD-0186", "name": "Zapatillas Converse Chuck Taylor All Star", "price": 249000, "category": "fashion", "subcategory": "shoes", "rating": 4.5, "in_stock": True, "trending": False, "description": "Zapatillas clasicas de lona con suela de caucho vulcanizado"},
    {"product_id": "PROD-0187", "name": "Mocasines de gamuza cafe", "price": 199000, "category": "fashion", "subcategory": "shoes", "rating": 4.3, "in_stock": True, "trending": False, "description": "Mocasines elegantes de gamuza con costura artesanal visible"},
    {"product_id": "PROD-0188", "name": "Tenis New Balance 574 clasicos", "price": 449000, "category": "fashion", "subcategory": "shoes", "rating": 4.5, "in_stock": True, "trending": False, "description": "Tenis retro con amortiguacion ENCAP y suela de goma durable"},
    {"product_id": "PROD-0189", "name": "Botines tacon bajo negro mujer", "price": 229000, "category": "fashion", "subcategory": "shoes", "rating": 4.2, "in_stock": True, "trending": False, "description": "Botines de tacon bajo con cremallera lateral y punta fina"},
    {"product_id": "PROD-0190", "name": "Crocs Classic Clog colores variados", "price": 169000, "category": "fashion", "subcategory": "shoes", "rating": 4.3, "in_stock": False, "trending": False, "description": "Zuecos livianos y comodos con material Croslite ventilado"},
    # -- bags --
    {"product_id": "PROD-0191", "name": "Bolso de cuero italiano marca Velez", "price": 389000, "category": "fashion", "subcategory": "bags", "rating": 4.6, "in_stock": True, "trending": True, "description": "Bolso de cuero genuino con compartimentos y forro interior"},
    {"product_id": "PROD-0192", "name": "Morral antirrobo USB laptop 15.6", "price": 169000, "category": "fashion", "subcategory": "bags", "rating": 4.5, "in_stock": True, "trending": True, "description": "Morral con cierre oculto y puerto USB externo para carga"},
    {"product_id": "PROD-0193", "name": "Bolso crossbody pequeno cadena dorada", "price": 129000, "category": "fashion", "subcategory": "bags", "rating": 4.3, "in_stock": True, "trending": False, "description": "Bolso pequeno con correa de cadena para uso casual o formal"},
    {"product_id": "PROD-0194", "name": "Maleta de viaje 4 ruedas 24 pulgadas", "price": 399000, "category": "fashion", "subcategory": "bags", "rating": 4.4, "in_stock": True, "trending": False, "description": "Maleta rigida con 4 ruedas giratorias y cerradura TSA"},
    {"product_id": "PROD-0195", "name": "Billetera de cuero genuino con RFID", "price": 89000, "category": "fashion", "subcategory": "bags", "rating": 4.5, "in_stock": True, "trending": False, "description": "Billetera con proteccion RFID y multiples compartimentos"},
    {"product_id": "PROD-0196", "name": "Bolso tote grande lona y cuero", "price": 199000, "category": "fashion", "subcategory": "bags", "rating": 4.3, "in_stock": True, "trending": False, "description": "Bolso tote espacioso de lona resistente con asas de cuero"},
    {"product_id": "PROD-0197", "name": "Mochila deportiva Nike Brasilia", "price": 149000, "category": "fashion", "subcategory": "bags", "rating": 4.4, "in_stock": True, "trending": False, "description": "Mochila deportiva con compartimento para zapatos y laptop"},
    {"product_id": "PROD-0198", "name": "Neceser de viaje organizador", "price": 79000, "category": "fashion", "subcategory": "bags", "rating": 4.2, "in_stock": True, "trending": False, "description": "Neceser impermeable con gancho colgante y multiples bolsillos"},
    {"product_id": "PROD-0199", "name": "Bolso de mano clutch fiesta", "price": 109000, "category": "fashion", "subcategory": "bags", "rating": 4.1, "in_stock": True, "trending": False, "description": "Clutch elegante con cierre magnetico y cadena desmontable"},
    {"product_id": "PROD-0200", "name": "Maletin ejecutivo cuero cafe", "price": 349000, "category": "fashion", "subcategory": "bags", "rating": 4.4, "in_stock": False, "trending": False, "description": "Maletin profesional de cuero con compartimento acolchado"},
    # -- jewelry --
    {"product_id": "PROD-0201", "name": "Collar de plata 925 con dije corazon", "price": 149000, "category": "fashion", "subcategory": "jewelry", "rating": 4.5, "in_stock": True, "trending": False, "description": "Collar de plata esterlina 925 con dije de corazon pulido"},
    {"product_id": "PROD-0202", "name": "Aretes argolla bano en oro 18k", "price": 89000, "category": "fashion", "subcategory": "jewelry", "rating": 4.3, "in_stock": True, "trending": True, "description": "Aretes de argolla con bano de oro de 18 kilates duradero"},
    {"product_id": "PROD-0203", "name": "Reloj Casio Vintage dorado A168WG", "price": 199000, "category": "fashion", "subcategory": "jewelry", "rating": 4.6, "in_stock": True, "trending": True, "description": "Reloj digital retro de acero inoxidable con bano dorado"},
    {"product_id": "PROD-0204", "name": "Pulsera de acero inoxidable eslabones", "price": 79000, "category": "fashion", "subcategory": "jewelry", "rating": 4.2, "in_stock": True, "trending": False, "description": "Pulsera de eslabones gruesos en acero inoxidable pulido"},
    {"product_id": "PROD-0205", "name": "Anillo de compromiso plata con circon", "price": 249000, "category": "fashion", "subcategory": "jewelry", "rating": 4.7, "in_stock": True, "trending": False, "description": "Anillo de plata 925 con piedra de circon brillante central"},
    {"product_id": "PROD-0206", "name": "Set de aretes y collar perlas naturales", "price": 329000, "category": "fashion", "subcategory": "jewelry", "rating": 4.4, "in_stock": True, "trending": False, "description": "Conjunto de perlas naturales de agua dulce con broche plata"},
    {"product_id": "PROD-0207", "name": "Reloj inteligente fashion dorado rosado", "price": 299000, "category": "fashion", "subcategory": "jewelry", "rating": 4.3, "in_stock": True, "trending": False, "description": "Smartwatch con diseno de joyeria y funciones de salud"},
    {"product_id": "PROD-0208", "name": "Cadena de plata 925 tejido cubano 50cm", "price": 189000, "category": "fashion", "subcategory": "jewelry", "rating": 4.5, "in_stock": True, "trending": False, "description": "Cadena de plata con tejido cubano grueso estilo urbano"},
    {"product_id": "PROD-0209", "name": "Piercing argolla nariz oro 14k", "price": 69000, "category": "fashion", "subcategory": "jewelry", "rating": 4.1, "in_stock": True, "trending": False, "description": "Piercing de nariz en oro 14 kilates hipoalergenico"},
    {"product_id": "PROD-0210", "name": "Gemelos de acero para camisa formal", "price": 99000, "category": "fashion", "subcategory": "jewelry", "rating": 4.2, "in_stock": False, "trending": False, "description": "Gemelos elegantes de acero inoxidable para camisas de gala"},
    # -- sportswear --
    {"product_id": "PROD-0211", "name": "Leggins deportivos de compresion mujer", "price": 99000, "category": "fashion", "subcategory": "sportswear", "rating": 4.5, "in_stock": True, "trending": True, "description": "Leggins de compresion con cintura alta y tela transpirable"},
    {"product_id": "PROD-0212", "name": "Camiseta dri-fit hombre Under Armour", "price": 129000, "category": "fashion", "subcategory": "sportswear", "rating": 4.4, "in_stock": True, "trending": False, "description": "Camiseta deportiva con tecnologia de secado rapido UAtech"},
    {"product_id": "PROD-0213", "name": "Short deportivo con malla interior", "price": 79000, "category": "fashion", "subcategory": "sportswear", "rating": 4.3, "in_stock": True, "trending": False, "description": "Short ligero con malla de compresion interior integrada"},
    {"product_id": "PROD-0214", "name": "Top deportivo soporte alto Nike", "price": 109000, "category": "fashion", "subcategory": "sportswear", "rating": 4.5, "in_stock": True, "trending": True, "description": "Top deportivo con soporte alto y tirantes ajustables"},
    {"product_id": "PROD-0215", "name": "Chaqueta rompevientos impermeable", "price": 199000, "category": "fashion", "subcategory": "sportswear", "rating": 4.4, "in_stock": True, "trending": False, "description": "Chaqueta ligera resistente al agua y viento con capucha"},
    {"product_id": "PROD-0216", "name": "Pantalon jogger slim algodon", "price": 119000, "category": "fashion", "subcategory": "sportswear", "rating": 4.3, "in_stock": True, "trending": False, "description": "Jogger con corte slim y punos elasticos en algodon suave"},
    {"product_id": "PROD-0217", "name": "Guantes de entrenamiento gym", "price": 59000, "category": "fashion", "subcategory": "sportswear", "rating": 4.2, "in_stock": True, "trending": False, "description": "Guantes con palma antideslizante y soporte para muneca"},
    {"product_id": "PROD-0218", "name": "Banda elastica de resistencia set 5", "price": 49000, "category": "fashion", "subcategory": "sportswear", "rating": 4.5, "in_stock": True, "trending": False, "description": "Set de 5 bandas de resistencia con diferentes niveles"},
    {"product_id": "PROD-0219", "name": "Gorra deportiva dry-fit ajustable", "price": 49000, "category": "fashion", "subcategory": "sportswear", "rating": 4.3, "in_stock": True, "trending": False, "description": "Gorra deportiva con tela transpirable y cierre ajustable"},
    {"product_id": "PROD-0220", "name": "Medias deportivas running pack de 6", "price": 59000, "category": "fashion", "subcategory": "sportswear", "rating": 4.4, "in_stock": False, "trending": False, "description": "Pack de medias acolchadas con soporte de arco para correr"},
    # ===================================================================
    # BEAUTY (~70 products) - PROD-0221 to PROD-0290
    # ===================================================================
    # -- skincare --
    {"product_id": "PROD-0221", "name": "Serum vitamina C The Ordinary 30ml", "price": 89000, "category": "beauty", "subcategory": "skincare", "rating": 4.7, "in_stock": True, "trending": True, "description": "Serum con acido ascorbico puro al 23% para piel luminosa"},
    {"product_id": "PROD-0222", "name": "Crema hidratante CeraVe 473ml", "price": 99000, "category": "beauty", "subcategory": "skincare", "rating": 4.8, "in_stock": True, "trending": True, "description": "Crema con ceramidas y acido hialuronico para restaurar la piel"},
    {"product_id": "PROD-0223", "name": "Protector solar La Roche-Posay SPF50+", "price": 119000, "category": "beauty", "subcategory": "skincare", "rating": 4.7, "in_stock": True, "trending": False, "description": "Proteccion solar de amplio espectro con acabado invisible"},
    {"product_id": "PROD-0224", "name": "Retinol serum antienvejecimiento 30ml", "price": 129000, "category": "beauty", "subcategory": "skincare", "rating": 4.5, "in_stock": True, "trending": False, "description": "Serum con retinol encapsulado para reducir lineas de expresion"},
    {"product_id": "PROD-0225", "name": "Agua micelar Bioderma Sensibio 500ml", "price": 79000, "category": "beauty", "subcategory": "skincare", "rating": 4.6, "in_stock": True, "trending": False, "description": "Agua micelar suave para piel sensible sin necesidad de enjuague"},
    {"product_id": "PROD-0226", "name": "Mascarilla facial de arcilla verde", "price": 49000, "category": "beauty", "subcategory": "skincare", "rating": 4.3, "in_stock": True, "trending": False, "description": "Mascarilla purificante de arcilla natural para poros abiertos"},
    {"product_id": "PROD-0227", "name": "Contorno de ojos con acido hialuronico", "price": 89000, "category": "beauty", "subcategory": "skincare", "rating": 4.4, "in_stock": True, "trending": False, "description": "Crema para contorno de ojos que reduce ojeras e hinchazones"},
    {"product_id": "PROD-0228", "name": "Tonico facial de niacinamida 200ml", "price": 69000, "category": "beauty", "subcategory": "skincare", "rating": 4.5, "in_stock": True, "trending": False, "description": "Tonico equilibrante con niacinamida al 10% para poros y brillo"},
    {"product_id": "PROD-0229", "name": "Exfoliante quimico AHA BHA 30ml", "price": 79000, "category": "beauty", "subcategory": "skincare", "rating": 4.4, "in_stock": True, "trending": False, "description": "Solucion exfoliante con acidos AHA y BHA para renovacion celular"},
    {"product_id": "PROD-0230", "name": "Kit de skincare The Ordinary completo", "price": 245000, "category": "beauty", "subcategory": "skincare", "rating": 4.6, "in_stock": False, "trending": True, "description": "Set completo de rutina facial con 5 productos The Ordinary"},
    # -- makeup --
    {"product_id": "PROD-0231", "name": "Base de maquillaje MAC Studio Fix 30ml", "price": 159000, "category": "beauty", "subcategory": "makeup", "rating": 4.5, "in_stock": True, "trending": True, "description": "Base de cobertura media a completa con acabado mate natural"},
    {"product_id": "PROD-0232", "name": "Paleta de sombras Urban Decay Naked", "price": 189000, "category": "beauty", "subcategory": "makeup", "rating": 4.7, "in_stock": True, "trending": True, "description": "Paleta de 12 sombras en tonos neutros con alta pigmentacion"},
    {"product_id": "PROD-0233", "name": "Labial liquido mate Maybelline SuperStay", "price": 49000, "category": "beauty", "subcategory": "makeup", "rating": 4.4, "in_stock": True, "trending": False, "description": "Labial de larga duracion hasta 16 horas sin transferencia"},
    {"product_id": "PROD-0234", "name": "Rimel de pestanas L'Oreal Lash Paradise", "price": 59000, "category": "beauty", "subcategory": "makeup", "rating": 4.5, "in_stock": True, "trending": False, "description": "Rimel con cepillo suave que alarga y da volumen a las pestanas"},
    {"product_id": "PROD-0235", "name": "Polvo compacto traslucido Laura Mercier", "price": 179000, "category": "beauty", "subcategory": "makeup", "rating": 4.6, "in_stock": True, "trending": False, "description": "Polvo suelto traslucido que fija el maquillaje sin peso"},
    {"product_id": "PROD-0236", "name": "Set de brochas maquillaje 15 piezas", "price": 89000, "category": "beauty", "subcategory": "makeup", "rating": 4.3, "in_stock": True, "trending": False, "description": "Kit profesional de brochas con pelo sintetico suave y estuche"},
    {"product_id": "PROD-0237", "name": "Corrector de ojeras Nars Radiant Creamy", "price": 139000, "category": "beauty", "subcategory": "makeup", "rating": 4.5, "in_stock": True, "trending": False, "description": "Corrector cremoso con cobertura buildable y acabado luminoso"},
    {"product_id": "PROD-0238", "name": "Iluminador liquido Charlotte Tilbury", "price": 199000, "category": "beauty", "subcategory": "makeup", "rating": 4.4, "in_stock": True, "trending": False, "description": "Iluminador con particulas finas para un brillo natural sutil"},
    {"product_id": "PROD-0239", "name": "Delineador de ojos resistente al agua", "price": 39000, "category": "beauty", "subcategory": "makeup", "rating": 4.3, "in_stock": True, "trending": False, "description": "Delineador de punta fina waterproof de larga duracion"},
    {"product_id": "PROD-0240", "name": "Primer facial pore minimizer 30ml", "price": 99000, "category": "beauty", "subcategory": "makeup", "rating": 4.4, "in_stock": False, "trending": False, "description": "Prebase que minimiza poros y prepara la piel para el maquillaje"},
    # -- haircare --
    {"product_id": "PROD-0241", "name": "Shampoo sin sulfatos Moroccanoil 250ml", "price": 129000, "category": "beauty", "subcategory": "haircare", "rating": 4.6, "in_stock": True, "trending": True, "description": "Shampoo con aceite de argan para cabello suave y brillante"},
    {"product_id": "PROD-0242", "name": "Aceite de argan tratamiento capilar 100ml", "price": 89000, "category": "beauty", "subcategory": "haircare", "rating": 4.5, "in_stock": True, "trending": False, "description": "Aceite multifuncional que nutre y protege el cabello del calor"},
    {"product_id": "PROD-0243", "name": "Plancha de cabello GHD Gold Professional", "price": 899000, "category": "beauty", "subcategory": "haircare", "rating": 4.7, "in_stock": True, "trending": True, "description": "Plancha profesional con placas ceramicas y calor optimo 185C"},
    {"product_id": "PROD-0244", "name": "Secador de cabello Dyson Supersonic", "price": 1999000, "category": "beauty", "subcategory": "haircare", "rating": 4.8, "in_stock": True, "trending": False, "description": "Secador con motor digital V9 y control inteligente de calor"},
    {"product_id": "PROD-0245", "name": "Mascarilla capilar keratina 500ml", "price": 69000, "category": "beauty", "subcategory": "haircare", "rating": 4.4, "in_stock": True, "trending": False, "description": "Tratamiento intensivo con keratina para cabello danado y seco"},
    {"product_id": "PROD-0246", "name": "Acondicionador reparador Pantene Pro-V", "price": 39000, "category": "beauty", "subcategory": "haircare", "rating": 4.3, "in_stock": True, "trending": False, "description": "Acondicionador con pro-vitaminas que repara dano visible"},
    {"product_id": "PROD-0247", "name": "Rizador automatico de cabello Babyliss", "price": 349000, "category": "beauty", "subcategory": "haircare", "rating": 4.4, "in_stock": True, "trending": False, "description": "Rizador automatico con 3 direcciones de rizo y calor rapido"},
    {"product_id": "PROD-0248", "name": "Tratamiento anticaida Nioxin System 2", "price": 159000, "category": "beauty", "subcategory": "haircare", "rating": 4.3, "in_stock": True, "trending": False, "description": "Sistema de tratamiento para cabello fino con adelgazamiento"},
    {"product_id": "PROD-0249", "name": "Cepillo desenredante Tangle Teezer", "price": 69000, "category": "beauty", "subcategory": "haircare", "rating": 4.5, "in_stock": True, "trending": False, "description": "Cepillo con cerdas flexibles que desenreda sin dolor ni quiebre"},
    {"product_id": "PROD-0250", "name": "Spray protector de calor 200ml", "price": 59000, "category": "beauty", "subcategory": "haircare", "rating": 4.3, "in_stock": False, "trending": False, "description": "Spray termoprotector que protege el cabello hasta 230 grados"},
    # -- fragrance --
    {"product_id": "PROD-0251", "name": "Perfume Carolina Herrera Good Girl 80ml", "price": 599000, "category": "beauty", "subcategory": "fragrance", "rating": 4.7, "in_stock": True, "trending": True, "description": "Perfume femenino con notas de jazmin y cacao en frasco iconico"},
    {"product_id": "PROD-0252", "name": "Colonia Versace Pour Homme 100ml", "price": 449000, "category": "beauty", "subcategory": "fragrance", "rating": 4.6, "in_stock": True, "trending": True, "description": "Fragancia masculina fresca con notas de ambar y almizcleno"},
    {"product_id": "PROD-0253", "name": "Perfume Chanel Coco Mademoiselle 50ml", "price": 699000, "category": "beauty", "subcategory": "fragrance", "rating": 4.8, "in_stock": True, "trending": False, "description": "Eau de parfum oriental fresco con notas de naranja y pachuli"},
    {"product_id": "PROD-0254", "name": "Body splash Victoria's Secret 250ml", "price": 149000, "category": "beauty", "subcategory": "fragrance", "rating": 4.3, "in_stock": True, "trending": False, "description": "Splash corporal con fragancia floral frutal de larga duracion"},
    {"product_id": "PROD-0255", "name": "Perfume Dior Sauvage EDT 100ml", "price": 549000, "category": "beauty", "subcategory": "fragrance", "rating": 4.7, "in_stock": True, "trending": False, "description": "Eau de toilette masculina fresca con pimienta de Calabria"},
    {"product_id": "PROD-0256", "name": "Set de miniaturas perfumes designer 5pcs", "price": 299000, "category": "beauty", "subcategory": "fragrance", "rating": 4.4, "in_stock": True, "trending": False, "description": "Coleccion de 5 miniaturas de perfumes de marcas reconocidas"},
    {"product_id": "PROD-0257", "name": "Perfume Lancome La Vie Est Belle 75ml", "price": 499000, "category": "beauty", "subcategory": "fragrance", "rating": 4.6, "in_stock": True, "trending": False, "description": "Perfume femenino con iris y praline en frasco de sonrisa"},
    {"product_id": "PROD-0258", "name": "Colonia Dolce & Gabbana Light Blue 125ml", "price": 399000, "category": "beauty", "subcategory": "fragrance", "rating": 4.5, "in_stock": True, "trending": False, "description": "Fragancia fresca mediterranea con manzana verde y cedro"},
    {"product_id": "PROD-0259", "name": "Difusor de aromas para hogar bambu", "price": 79000, "category": "beauty", "subcategory": "fragrance", "rating": 4.2, "in_stock": True, "trending": False, "description": "Difusor con varillas de bambu y aceite esencial de larga duracion"},
    {"product_id": "PROD-0260", "name": "Perfume Ralph Lauren Polo Blue 125ml", "price": 389000, "category": "beauty", "subcategory": "fragrance", "rating": 4.4, "in_stock": False, "trending": False, "description": "Eau de toilette masculina acuatica con notas de melon y salvia"},
    # -- body_care --
    {"product_id": "PROD-0261", "name": "Crema corporal hidratante Nivea 400ml", "price": 39000, "category": "beauty", "subcategory": "body_care", "rating": 4.4, "in_stock": True, "trending": False, "description": "Crema corporal con formula nutritiva para piel suave todo el dia"},
    {"product_id": "PROD-0262", "name": "Desodorante natural sin aluminio", "price": 49000, "category": "beauty", "subcategory": "body_care", "rating": 4.3, "in_stock": True, "trending": False, "description": "Desodorante con ingredientes naturales sin sales de aluminio"},
    {"product_id": "PROD-0263", "name": "Gel de bano exfoliante cafe 500ml", "price": 59000, "category": "beauty", "subcategory": "body_care", "rating": 4.5, "in_stock": True, "trending": True, "description": "Gel exfoliante con particulas de cafe que activa la circulacion"},
    {"product_id": "PROD-0264", "name": "Manteca corporal de karite pura 200g", "price": 69000, "category": "beauty", "subcategory": "body_care", "rating": 4.6, "in_stock": True, "trending": False, "description": "Manteca de karite 100% natural para hidratacion profunda"},
    {"product_id": "PROD-0265", "name": "Kit de depilacion cera tibia", "price": 89000, "category": "beauty", "subcategory": "body_care", "rating": 4.2, "in_stock": True, "trending": False, "description": "Kit completo con calentador de cera y bandas depilatorias"},
    {"product_id": "PROD-0266", "name": "Aceite corporal de coco organico 250ml", "price": 59000, "category": "beauty", "subcategory": "body_care", "rating": 4.5, "in_stock": True, "trending": False, "description": "Aceite de coco prensado en frio para cuerpo y cabello"},
    {"product_id": "PROD-0267", "name": "Jabon artesanal set de 4 aromas", "price": 49000, "category": "beauty", "subcategory": "body_care", "rating": 4.4, "in_stock": True, "trending": False, "description": "Jabones artesanales con ingredientes naturales y aceites"},
    {"product_id": "PROD-0268", "name": "Crema para manos y unas 100ml", "price": 39000, "category": "beauty", "subcategory": "body_care", "rating": 4.3, "in_stock": True, "trending": False, "description": "Crema nutritiva que fortalece unas y suaviza manos secas"},
    {"product_id": "PROD-0269", "name": "Locion bronceadora gradual 200ml", "price": 69000, "category": "beauty", "subcategory": "body_care", "rating": 4.2, "in_stock": True, "trending": False, "description": "Locion autobronceante gradual con efecto natural sin manchas"},
    {"product_id": "PROD-0270", "name": "Esponja de bano natural tipo konjac", "price": 29000, "category": "beauty", "subcategory": "body_care", "rating": 4.1, "in_stock": False, "trending": False, "description": "Esponja biodegradable de konjac para limpieza facial suave"},
    # -- tools --
    {"product_id": "PROD-0271", "name": "Espejo de aumento con luz LED 10x", "price": 119000, "category": "beauty", "subcategory": "tools", "rating": 4.5, "in_stock": True, "trending": True, "description": "Espejo con aumento 10x y luz LED para maquillaje de precision"},
    {"product_id": "PROD-0272", "name": "Kit de manicure profesional 18 piezas", "price": 89000, "category": "beauty", "subcategory": "tools", "rating": 4.4, "in_stock": True, "trending": False, "description": "Set completo de manicure y pedicure en estuche de cuero"},
    {"product_id": "PROD-0273", "name": "Rodillo facial jade y gua sha set", "price": 69000, "category": "beauty", "subcategory": "tools", "rating": 4.3, "in_stock": True, "trending": True, "description": "Set de masaje facial de jade natural para drenaje linfatico"},
    {"product_id": "PROD-0274", "name": "Lampara UV para unas gel 48W", "price": 129000, "category": "beauty", "subcategory": "tools", "rating": 4.4, "in_stock": True, "trending": False, "description": "Lampara profesional LED UV para secado rapido de unas en gel"},
    {"product_id": "PROD-0275", "name": "Cortadora de cabello Wahl profesional", "price": 199000, "category": "beauty", "subcategory": "tools", "rating": 4.6, "in_stock": True, "trending": False, "description": "Maquina cortapelo profesional con motor electromagnetico"},
    {"product_id": "PROD-0276", "name": "Depiladora electrica Braun Silk-epil", "price": 299000, "category": "beauty", "subcategory": "tools", "rating": 4.5, "in_stock": True, "trending": False, "description": "Depiladora inalambrica con cabezal flexible y uso en ducha"},
    {"product_id": "PROD-0277", "name": "Limpiador facial ultrasonico", "price": 149000, "category": "beauty", "subcategory": "tools", "rating": 4.3, "in_stock": True, "trending": False, "description": "Dispositivo de limpieza facial por vibracion ultrasonica"},
    {"product_id": "PROD-0278", "name": "Vaporizador facial con ozono portatil", "price": 99000, "category": "beauty", "subcategory": "tools", "rating": 4.2, "in_stock": True, "trending": False, "description": "Vaporizador que abre poros y prepara la piel para tratamientos"},
    {"product_id": "PROD-0279", "name": "Pinzas de cejas set profesional 4 piezas", "price": 39000, "category": "beauty", "subcategory": "tools", "rating": 4.4, "in_stock": True, "trending": False, "description": "Set de pinzas de acero inoxidable con diferentes puntas"},
    {"product_id": "PROD-0280", "name": "Masajeador facial electrico V-line", "price": 109000, "category": "beauty", "subcategory": "tools", "rating": 4.1, "in_stock": False, "trending": False, "description": "Dispositivo de micromasaje facial con EMS para reafirmar"},
    # -- sets --
    {"product_id": "PROD-0281", "name": "Set de regalo skincare coreana 7 pasos", "price": 249000, "category": "beauty", "subcategory": "sets", "rating": 4.6, "in_stock": True, "trending": True, "description": "Kit completo de rutina coreana con 7 productos esenciales"},
    {"product_id": "PROD-0282", "name": "Kit de maquillaje basico principiante", "price": 179000, "category": "beauty", "subcategory": "sets", "rating": 4.4, "in_stock": True, "trending": False, "description": "Set de inicio con base, rimel, labial y brochas incluidas"},
    {"product_id": "PROD-0283", "name": "Set de perfumeria miniatura mujer 5pcs", "price": 199000, "category": "beauty", "subcategory": "sets", "rating": 4.5, "in_stock": True, "trending": True, "description": "Coleccion de 5 perfumes femeninos en tamano miniatura"},
    {"product_id": "PROD-0284", "name": "Kit spa en casa relajante completo", "price": 149000, "category": "beauty", "subcategory": "sets", "rating": 4.3, "in_stock": True, "trending": False, "description": "Kit con sales de bano, vela, mascarilla y aceite esencial"},
    {"product_id": "PROD-0285", "name": "Set de cuidado para barba premium", "price": 119000, "category": "beauty", "subcategory": "sets", "rating": 4.5, "in_stock": True, "trending": False, "description": "Kit con aceite, balsamo, peine y cepillo para barba"},
    {"product_id": "PROD-0286", "name": "Kit de viaje beauty essentials", "price": 99000, "category": "beauty", "subcategory": "sets", "rating": 4.4, "in_stock": True, "trending": False, "description": "Set de viaje con envases recargables y neceser transparente"},
    {"product_id": "PROD-0287", "name": "Set de bano aromatico lavanda 6 piezas", "price": 89000, "category": "beauty", "subcategory": "sets", "rating": 4.3, "in_stock": True, "trending": False, "description": "Set de bano con gel, crema, sales, jabon, esponja y bolsa"},
    {"product_id": "PROD-0288", "name": "Kit de unas gel colores basicos 12pcs", "price": 139000, "category": "beauty", "subcategory": "sets", "rating": 4.2, "in_stock": True, "trending": False, "description": "Set de esmaltes en gel con 12 colores clasicos y acabados"},
    {"product_id": "PROD-0289", "name": "Set de cuidado capilar completo 4 pzas", "price": 169000, "category": "beauty", "subcategory": "sets", "rating": 4.4, "in_stock": True, "trending": False, "description": "Kit con shampoo, acondicionador, mascarilla y serum capilar"},
    {"product_id": "PROD-0290", "name": "Pack de mascarillas faciales 7 dias", "price": 59000, "category": "beauty", "subcategory": "sets", "rating": 4.5, "in_stock": False, "trending": False, "description": "Pack de 7 mascarillas de tela con ingredientes diferentes"},
]
